### ISSUE TITLE
update Strelka to Strelka2

### ISSUE THREAD

**Issue by jasonwalker80** [genome/arvados_trial#54]
https://github.com/Illumina/strelka/releases/latest

**Comment by tmooney** [comment]
Should we consider using the [`--region` option](https://github.com/Illumina/strelka/blob/c8838779ba6b5de6fc1e079a200b8a8e58dd814d/src/python/lib/strelkaSharedOptions.py#L81-L86) instead of post-process filtering?  These command-lines could get really long!

**Comment by malachig** [comment]
Is there a place in the strelka docs where these parameters are listed? If not how did you review them to find this option?

It sounds like we would have to be careful with this caveat: "All regions must be non-overlapping to get a meaningful result."

I guess the basic functionality is there.  We could also make a PR to strelka team that allows you to provide regions of interest in a file instead of a long command line string.

**Comment by malachig** [comment]
https://github.com/Illumina/strelka/issues/1
